### ISSUE TITLE
Reduce error verbosity

### ISSUE THREAD

**Issue by mrdgo** [ddanier/nur#34]
I'm not so happy about the latest changes to nu's output in case of an error. But that's not the main point. In nur, when a command fails, I get nu's error description twice - once for the actual command and once from nur.

![image](https://github.com/user-attachments/assets/18d35220-94a6-4594-82da-d88bd8ff59ad)

To me, this is too much text that doesn't have the information I'm looking for. In my ideal world, this would only be displayed once.

**Comment by ddanier** [comment]
I think you are using `nu` shell >=0.98.0, right?

Because in never versions `nu` shell will display such a stack trace for every failed command you execute. See this example:

```
nu ❯ $env.config.display_errors.exit_code = true

nu ❯ ^false
Error: nu::shell::non_zero_exit_code

  × External command had a non-zero exit code
   ╭─[entry #31:1:2]
 1 │ ^false
   ·  ──┬──
   ·    ╰── exited with code 1
   ╰────


nu ❯ $env.config.display_errors.exit_code = false

nu ❯ ^false
```

You see that `nu` will create this strack trace when calling `^false` if `$env.config.display_errors.exit_code` is set to `true`.

Same applies to calling `nur` as the external command. Let's say I create a task that is defined like this:

```
def "nur debug-error" [] {
    ^false
}
```

Now it also depends on `$env.config.display_errors.exit_code` whether you will get this second trace for the error.

```
nu ❯ $env.config.display_errors.exit_code = true

nu ❯ nur debug-error
nur version 0.10.0
Project path: /Users/ddanier/work/nur
Executing task: debug-error

Error: nu::shell::non_zero_exit_code

  × External command had a non-zero exit code
    ╭─[/Users/ddanier/work/nur/nurfile.local:63:6]
 62 │ def "nur debug-error" [] {
 63 │     ^false
    ·      ──┬──
    ·        ╰── exited with code 1
 64 │ }
    ╰────

Task execution failed (exit code: 1)
Error: nu::shell::non_zero_exit_code

  × External command had a non-zero exit code
   ╭─[entry #35:1:1]
 1 │ nur debug-error
   · ─┬─
   ·  ╰── exited with code 1
   ╰────


nu ❯ $env.config.display_errors.exit_code = false

nu ❯ nur debug-error
nur version 0.10.0
Project path: /Users/ddanier/work/nur
Executing task: debug-error

Error: nu::shell::non_zero_exit_code

  × External command had a non-zero exit code
    ╭─[/Users/ddanier/work/nur/nurfile.local:63:6]
 62 │ def "nur debug-error" [] {
 63 │     ^false
    ·      ──┬──
    ·        ╰── exited with code 1
 64 │ }
    ╰────

Task execution failed (exit code: 1)
```

So `nur` itself is only generating one error. But if you use `nu` as your shell it will also create an error for the call to `nur`.

Sadly I cannot control the `nu` behaviour from `nur`. Also it does not make much sense to remove the error from `nur` itself, as it contains the most useful details about the actual error.

I personally switched my shell to be using `$env.config.display_errors.exit_code = false` like the 0.98.0 release notes suggests. Also note that this is the default behaviour if you reinstall `nu`, just makes the most sense this way.

See https://www.nushell.sh/blog/2024-09-17-nushell_0_98_0.html#non-zero-exit-codes-are-now-errors-toc for the note about changing the config after the upgrade and https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L177 for the new default config you get on a vanilla `nu` install.

Quote:
> In the default config, this error is suppressed in the REPL. However, if you are upgrading with an existing config, you must add this section to your $env.config to suppress this error: ...

**Comment by ddanier** [comment]
@mrdgo Any feedback? Would you prefer `nur` having an option to turn off the error trace as well? Is this all fine for you now?

**Comment by mrdgo** [comment]
Thanks for your thorough answer!

I was aware of most of your reply. I was unaware that `^command` could or should suppress nu's verbosity - I use that in my `nurfile` but it still outputs that error message. I'll dig into this a bit. I'd reopen, if there is another issue :)

**Comment by ddanier** [comment]
@mrdgo Just to be clear about this:
`^` does not suppress the errors. I used `^false` to execute the external command `/usr/bin/false`, which will always have a non zero exit code. The `^` is to avoid using the boolean value `false` that `nu` provides. It does not change the verbosity.

See https://www.nushell.sh/book/escaping.html for details.
